### ISSUE TITLE
Fatal error when Deactivating & Activating

### ISSUE THREAD

**Issue by send-your-nudes** [Sama34/OUGC-Pages#19]
**Describe the bug**
An error which doesn't allow a plugin to be activated. (Previous version working fine)

```
[13-Jan-2019 23:46:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function update_query() on null in /home/xx/public_html/inc/plugins/ougc_pages.php:178
Stack trace:
#0 /home/xx/public_html/admin/modules/config/plugins.php(435): ougc_pages_activate()
#1 /home/xx/public_html/admin/index.php(821): require('/home/xx/...')
#2 {main}
  thrown in /home/xx/public_html/inc/plugins/ougc_pages.php on line 178
```

**To Reproduce**
1. Go to '...' Plugins
2. Click on '....'Deactive
3. Activate

**Expected behavior**
Activating.

**Comment by Pablito89** [comment]
same for me

**Comment by Sama34** [comment]
Sorry, just noticed this one. I have pushed a fix.
